### PR TITLE
fix: ensure short-lived message listeners are not removed prematurely

### LINKED ISSUE #40: clients/TypeScript: Remove or document invalid use of `InteractionContext` with standalone queries
#### Describe your idea, in simple words.
https://github.com/KtorZ/cardano-ogmios/pull/37#discussion_r627042048

#### Why is it a good idea?
https://github.com/KtorZ/cardano-ogmios/pull/37#discussion_r626759455

#### Are you willing to work on it yourself?
Yes

### PR DESCRIPTION
**Pull request by rhyslbw**
- adds a `Query` function to DRY up the code
- replaces self-removing event listeners, for the request-response
interactions, with manual removal of the listener after the handler
resolves.
- adds a test case to demonstrate concurrency when making state queries,
via the client.

Closes #40

### CODE REVIEW

File: clients/TypeScript/packages/client/src/StateQuery/Query.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+        async function listener (data: Data) {
+          const queryResponse = JSON.parse(data as string) as QueryResponse
+          if (queryResponse.reflection?.requestId !== requestId) { return }
+          await response.handler(
+            queryResponse,
+            resolve,
+            reject
+          )
+          socket.removeListener('message', listener)
```
Comment (rhyslbw) [inline clients/TypeScript/packages/client/src/StateQuery/Query.ts:36]: The listener is now removed _after_ execution is complete...

File: clients/TypeScript/packages/client/test/StateQuery.test.ts [hunk 2]
```diff
@@ -129,6 +129,19 @@ describe('Local state queries', () => {
 
         await client.release()
       })
+
+      it('can handle concurrent requests ', async () => {
+        const client = await createStateQueryClient({ connection })
+        const [currentEpoch, eraStart, ledgerTip] = await Promise.all([
```
Comment (KtorZ) [inline clients/TypeScript/packages/client/test/StateQuery.test.ts:135]: :+1:

**Review by KtorZ — APPROVED** [review]
